version: '3'

services:
    app:
        restart: always
        build:
            context: .
            args:
                SECRET_KEY: $SECRET_KEY
        environment:
            - SECRET_KEY=$SECRET_KEY
            - EMAIL_HOST_USER=$EMAIL_HOST_USER
            - EMAIL_HOST_PASSWORD=$EMAIL_HOST_PASSWORD
        volumes:
            - ./shared:/app/shared
    db:
        restart: always
        image: postgres:10.3-alpine
        environment:
            - POSTGRES_USER=amigcamel
        volumes:
            - /srv/aji/data:/var/lib/postgresql/data
