version: '3'

services:
    app:
        restart: always
        build:
            context: .
            args:
                SECRET_KEY: $SECRET_KEY
        command: uwsgi --socket shared/aji.sock --wsgi-file aji/wsgi.py --chmod-socket=666
        volumes:
            - ./shared:/app/shared
    db:
        restart: always
        image: postgres:10.3-alpine
        environment:
            - POSTGRES_USER=amigcamel
        volumes:
            - ./shared/data:/var/lib/postgresql/data
