version: '3'

services:
    app:
        restart: always
        build: .
        command: uwsgi --socket /tmp/aji/aji.sock --wsgi-file aji/wsgi.py --chmod-socket=666
        volumes:
            - /tmp/aji:/tmp/aji
            - /tmp/aji/static_all:/app/static_all
    db:
        restart: always
        image: postgres:10.3-alpine
        environment:
            - POSTGRES_USER=amigcamel
        volumes:
            - ./data:/var/lib/postgresql/data
